services:
  - type: web
    name: app3-soler-segu-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
